### ISSUE TITLE
Restricted channel access set for 'police', 'ems', 'doctor'.   qb-core/shared.lua uses 'ambulance'

### ISSUE THREAD

**Issue by sinfuljosh** [qbcore-framework/qb-radio#1]
https://github.com/qbcore-framework/qb-radio/blob/29f84fa8f2e4e2b301f86072839ae248755b3386/client.lua#L99

qb-radio's 'joinradio' uses 'ems' as the job authorized for restricted radio access. 
qb-core/shared.lua does not have 'ems' but does use 'ambulance'

**Comment by ihyajb** [comment]
Fixed. Its now set to just `police` and `ambulance`
