### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by bosskitz** [qbcore-framework/qb-radio#2]
Is there a way to lower the volume? Thank you

**Comment by AvarianKnight** [comment]
This is just a note for anyone in the future that decides to work on this, this can be done with [setRadioVolume](https://github.com/AvarianKnight/pma-voice/blob/main/docs/client-setters/setRadioVolume.md)

**Comment by SamShanks1** [comment]
Can try test this https://github.com/AvarianKnight/pma-voice/pull/150
