### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-radio#22]
Just downloaded and got this error

`[     script:qb-radio] Error loading script server.lua in resource qb-radio: citizen:/scripting/lua/scheduler.lua:881: No such export addChannelCheck in resource pma-voice
[     script:qb-radio] stack traceback:
[     script:qb-radio]  [C]: in function 'error'
[     script:qb-radio]  citizen:/scripting/lua/scheduler.lua:881: in metamethod 'index'
[     script:qb-radio]  @qb-radio/server.lua:24: in main chunk`

**Comment by BerkieBb** [comment]
Update pma-voice

**Comment by KingRyuShin** [comment]
it is updated to version v6.3.0 and i still receive that error

**Comment by BerkieBb** [comment]
And are your artifacts updated?

**Comment by Giana** [comment]
Same issue here, and artifacts are updated.

**Comment by tensenai** [comment]
> Just downloaded and got this error
> 
> `[ script:qb-radio] Error loading script server.lua in resource qb-radio: citizen:/scripting/lua/scheduler.lua:881: No such export addChannelCheck in resource pma-voice [ script:qb-radio] stack traceback: [ script:qb-radio] [C]: in function 'error' [ script:qb-radio] citizen:/scripting/lua/scheduler.lua:881: in metamethod 'index' [ script:qb-radio] @qb-radio/server.lua:24: in main chunk`



> Same issue here, and artifacts are updated.


Had same issue. In your config make sure your pma-voice loads before [qb]/qb-radio resource.

**Comment by BerkieBb** [comment]
Update your artifacts to 5181 or higher and update pma-voice

**Comment by tensenai** [comment]
> Update your artifacts to 5181 or higher and update pma-voice aswell

both were updated on my end. it was issue with pma-voice resource loading after qb-radio per the server.cfg

**Comment by ItsANoBrainer** [comment]
Resolved

**Comment by Luci-Garage** [comment]
> Resolved

How did you fixed that?
