### ISSUE TITLE
[SUGGESTION] Update radio model (NUI) + Frequency Saving

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-radio#32]
**Is your feature request related to a problem? Please describe.**
Would be nice to upgrade the radio "model" to something more modern and then tie in some added features to match this modern version.

**Describe the feature you'd like**
- Update radio image to something more modern
- Add ability to enter frequencies and save/name them, either within the radio screen like you do now to enter a frequency, or via qb-menu or something.

**Describe alternatives you've considered**
Replacing with 3rd party radio script, but yuck.

**Additional context**

**Comment by JensGryspeert** [comment]
I'm interested to do this. Sounds very good. Up to the maintainers if they wants to pull the request but I'll start to make this. Good suggestion!

**Comment by nzkfc** [comment]
I made one a few month ago I can PR

**Comment by JensGryspeert** [comment]
Go ahead.

**Comment by nzkfc** [comment]
#41

**Comment by GhzGarage** [comment]
https://github.com/qbcore-framework/qb-radio/pull/41
