### ISSUE TITLE
[BUG] Radio channel "rocker" only goes up/down 1 channel?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-radio#35]
**Describe the bug**
Using the channel up/down button only goes up and down one channel, on spamming button it just repeats the same number over and over without changing your channel.

**To Reproduce**
1. Join channel 100
2. Press up channel button once, says 101, push it again, says 101 still not 102.
3. Same thing for down.

**Expected behavior**
Pressing up and down should go up.... and down...

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No (Fresh QB)
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by endernation101** [comment]
Same thing is happening with me, im not sure if its on PMA-Voices side or the radio.

**Comment by GodyFromDiscord** [comment]
Fixed in PR 38
