### ISSUE TITLE
[SUGGESTION] TX Inhibit/Busy Channel Tone

### ISSUE THREAD

**Issue by BoogeyMan11588** [qbcore-framework/qb-radio#42]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
N/A

**Describe the feature you'd like**
A clear and concise description of what you want to happen. and with as much detail as possible how it would function in your opinion. Please try to keep it unique.
Feature would be to play a continuous tone and block the channel from being used if someone is already using the channel.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered for people to have in mind just in case the main idea isn't liked but a derivative is.
Finding a free, open source script.

**Additional context**

**Comment by Sharkiiie** [comment]
That does sound like a fun idea.
I might look into this :P

**Comment by Sharkiiie** [comment]
https://github.com/qbcore-framework/qb-radio/assets/8964613/beda34a4-a74c-441a-bf00-8bfd91f7d120

😉

**Comment by BoogeyMan11588** [comment]
I love it, hopefully the maintainers implement this and the modernized look. The would sweeten the whole deal.

**Comment by Sharkiiie** [comment]
The notification is from ox_lib, if you want that style.
I'm sorting out a potential bug, once that is done I will submit a PR to pma-voice, where the logic for this is actually handled.

No guarantee they will actually merge the PR, since that's not a QB thing.

**Comment by BoogeyMan11588** [comment]
I had originally opened this request there. 🥲
I just use the standard qbnotify. Great work non the less.
