### ISSUE TITLE
[BUG] Can't listen each other

### ISSUE THREAD

**Issue by VRSDevelopment** [qbcore-framework/qb-radio#44]
We Can't listen each other on radio, even our mic is working fine, we both talk with normal voice. but radio not work

**Comment by CapnDeath82** [comment]
Confirmed version 6683, mobile phone works fine but not the radio.. using left alt and both people on channel 13.

**Comment by jigglyblunt** [comment]
same here, no radio voice only phone and personal distance

**Comment by WPinzonDev** [comment]
same problem
