### ISSUE TITLE
Radios not working. Voice chat works fine, phones work fine. No voice in radio.

### ISSUE THREAD

**Issue by aopbags** [qbcore-framework/qb-radio#45]
I've tried just about every thing. Adding to server cfg, trying new scripts. Restarting resource. No issues in console either so Im really not sure on the issue.

**Comment by MentalIllness** [comment]
> I've tried just about every thing. Adding to server cfg, trying new scripts. Restarting resource. No issues in console either so Im really not sure on the issue.

Hi, can you attach some screenshots/videos? Seems like a local issue for me. Also you can find a faster support in our "fivem-support' thread in the Discord server. ( https://discord.gg/qbcore )

Mental Illness ~ QBCore Developer

**Comment by aldude999** [comment]
Same issue, me and a friend tried using it the other day, phone works fine, voice chat works fine, but when we were both on the same frequency, and tried to talk on the radio no audio came through. We could hear the beeping at the end of the transmission though.

**Comment by MentalIllness** [comment]
What script are you using for communication ( voice chat )?

**Comment by WPinzonDev** [comment]
Same problem but, I realized while testing with a friend, that when the game's microphone settings are open and not on push-to-talk, the radio works. However, I doubt that people want to go with the microphone open all the time, normally we all use push to talk.

**Comment by XFruzzi** [comment]
i don’t know if yall will ever see this i’m having a similar issue where everyone else is fine they can talk over radio and hear each other i can hear them but i cant talk over it and they cant hear me despite having the key binded! How did you guys ever fix it
