### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tah5882** [qbcore-framework/qb-radio#46]
**Describe the bug**
Vulnerability to connect to 1 MHz without being a government employee

**To Reproduce**
1. open radio
2. Click △
3. Can be connected to 1 MHz

**Expected behavior**
You have to be a government employee to be able to connect.

**Screenshots**
![image](https://github.com/qbcore-framework/qb-radio/assets/110086642/56c45484-5cc9-4ee8-a0d1-b70a1d8580c8)

**Questions (please complete the following information):**
 - now
 - qb-target, qb-smallresource
 - no

**Comment by itismejoey** [comment]
In addition, the UI does not update when you click the arrows to change the channel. 
https://gyazo.com/a9647418bb75ab2962d8e3c68b742f63

**Comment by Cocodrulo** [comment]
Fixed in new PR

**Comment by Cocodrulo** [comment]
Waiting merge

**Comment by tah5882** [comment]
Thank you all.
