### ISSUE TITLE
bug Spamming the alt button to speak on the radio

### ISSUE THREAD

**Issue by titicarabina** [qbcore-framework/qb-radio#9]
Spamming the alt button to speak on the radio and running at the same time and makes you and the players around you fall down . THIS IS A MAJOR BUG PLEASE TAKE A LOOK . Try to connect to a radio channel , and then run with shift and spam the alt button to speak on the radio. IF you are alone , nothing happenes , but if you are with players around you ALL of you fall down at the same time .

**Comment by IdrisDose** [comment]
I think this is a conflict with tackle, try changing the default tackle key / radio key.
